### ISSUE TITLE
Bug: Is it cryptography required?

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-cli#131]
### What happened?

Cannot load the keys during the ceremony in a fresh installation

```shell
╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                     STEP 2: Load roles keys                                      ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

The keys must have a password, and the file must be accessible.                                     

Depending on the Organization, each key has an owner, and each owner should insert the password     
personally.                                                                                         

The Ceremony process doesn't show the password or key content.                                      

Ready to start loading the keys? Passwords will be required for keys [y/n]: y

Enter 1/2 the root`s Key path: tests/files/JanisJoplin.key
Enter 1/2 the root`s Key password: 
❌ Failed: RSA key support requires the cryptography library
Try again? [y/n] (y): y

Enter 1/2 the root`s Key path: tests/files/JanisJoplin.key
Enter 1/2 the root`s Key password: 
❌ Failed: RSA key support requires the cryptography library
Try again? [y/n] (y): y

Enter 1/2 the root`s Key path: tests/files/JanisJoplin.key
```

### What steps did you take?

1. Use clean setup
2. Add the CLI
3. Login (`rstuf admin login`)
4. Run the ceremony (`rstuf admin ceremony`)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KAUTH** [comment]
I verified this as well.

The `cryptography` package is a dependency of the `securesystemslib` package, to be exact it is an _optional_ dependency (https://github.com/secure-systems-lab/securesystemslib/issues/482). Therefore, we need to install at least the `crypto` _extra_ (we should check if we are using any other features as well from `securesystemslib`).

With my PR fix I don't see this error, but following the same steps as above I get:
```shell
❌ Failed: Invalid encrypted file. Check the password.
```
This might have to do with my key however, can someone verify the fix from their side?
