### ISSUE TITLE
Task: simplify ceremony to use one online key for all roles except root

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf-cli#196]
### What is the task about?

We need to simplify the ceremony process by:
1. Removing questions about the number of keys and threshold for all roles except root.
2. Removing questions asking for information to load keys for all roles except root. 
3. Add questions to gather information about how to load the online key.
4. Remove all key information from the payload.

In order to load the online key in RSTUF worker you should configure the keyvault properly.

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/207

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Closed by #201
