### ISSUE TITLE
typo: Bootstrap

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-cli#71]
https://github.com/kaprien/tuf-repository-service-cli/blob/dbe986105060513f6765df76f396733b2b722940/tuf_repository_service/cli/admin/ceremony.py#L480

https://github.com/kaprien/tuf-repository-service-cli/blob/dbe986105060513f6765df76f396733b2b722940/tuf_repository_service/cli/admin/ceremony.py#L502

**Comment by MVrachev** [comment]
I can fix this.
